from tkinter import Tk, Button, Frame, messagebox, Label, Entry

ventana = Tk()
ventana.title("Caja Popular")
ventana.geometry("600x400")
seccion1 = Frame(ventana, bg = "orange")
seccion1.pack(expand=True, fill="both")
bienvenida = Label(seccion1, text="CAJA UPQ", bg="orange", font="consolas 20 bold")
bienvenida.pack()
seccion2 = Frame(ventana, bg= "white")
seccion2.pack(expand=True, fill="both")
Cuenta = Label(seccion1, text="No. de Cuenta:", font="Arial 12", bg="orange")
Cuenta.place(x=190, y=60)
Titular = Label(seccion1, text="Titular:", font="Arial 12", bg="orange")
Titular.place(x=248, y=80)
Edad = Label(seccion1, text="Edad:", font="Arial 12", bg="orange")
Edad.place(x=252, y=110)
SaldoI = Label(seccion1, text="Saldo Inicial:", font="Arial 12", bg="orange")
SaldoI.place(x=206, y=130)
Cuenta2= Entry(seccion1)
Cuenta2.place(x=300, y=60)
Titular2= Entry(seccion1)
Titular2.place(x=300, y=85)
Edad2= Entry(seccion1)
Edad2.place(x=300, y=110)
SaldoI2= Entry(seccion1)
SaldoI2.place(x=300, y=135)
ventana.mainloop()   
